export const chapters = [
  {
    id: 'network',
    number: '01',
    title: 'Một phản hồi, hai kết quả',
    category: 'Mạng',
    summary: 'Endpoint cục bộ phản hồi: mẫu thoát. Endpoint không tới được: chuỗi hành vi tiếp tục.',
    observed: 'A: PID 6520 nhận 155 byte rồi thoát 0; ba decoy giữ nguyên hash, không có service mới. B: PID 5152 và 5272 có tổng tám TCP Reconnect tới 127.0.0.1:80. Burp ghi HTTP 200 với Content-Length: 3.',
    mechanism: 'Trong lab, hosts ánh xạ domain kill-switch về loopback; cổng 80 được chuyển tới responder ở 127.0.0.1:8081. Procmon ghi sự kiện socket, Burp ghi HTTP. Một request của mẫu được tách khỏi ba preflight bằng timestamp và log. Hai phép thử ngày 08/10/2026, UTC+7, đối chiếu trạng thái endpoint với kết quả thực thi.',
    inference: 'Sự đối lập A/B hỗ trợ vai trò kill switch của khả năng tới endpoint; chưa xác định câu lệnh nhánh nội bộ.',
    limit: '155 byte là độ dài TCP Receive, không phải Content-Length. Không có hook chứng minh mẫu đọc status 200. Không coi request này là C2; ba decoy không đổi không chứng minh toàn máy bất biến.',
    evidence: [
      {
        id: 'E01',
        file: '/screenshots/A_burp_item4_host_verified_vmware.png',
        title: 'Phản hồi HTTP trong lab',
        caption: 'Burp item 4 hiển thị request, HTTP 200, Content-Length: 3 và forwarding host. Burp không chứa PID; attribution dựa trên timestamp, Procmon và log responder.',
        source: 'Burp item 4; mock_200.log; A_200.csv R475',
      },
      {
        id: 'E02',
        file: '/screenshots/A_run_direct_launch_1143_vmware.png',
        title: 'Mẫu thoát ở kịch bản A',
        caption: 'Transcript PowerShell hiển thị PID, exited và exit_code. Đây không phải cửa sổ Procmon; mốc thoát chính xác lấy từ CSV.',
        source: 'run_A_200.log; A_200.csv R343, R479',
      },
    ],
    records: [
      { time: '11:44:16.9469731', event: 'PID 6520: Process Start.', source: 'A_200.csv R343' },
      { time: '11:44:17.8177930', event: 'PID 6520: TCP Receive, Length: 155.', source: 'A_200.csv R475' },
      { time: '11:44:17.8391858', event: 'PID 6520: Process Exit, status 0.', source: 'A_200.csv R479' },
    ],
    terms: [
      { token: '127.0.0.1', meaning: 'Loopback của chính máy quan sát, không phải địa chỉ máy chủ bên ngoài.' },
      { token: 'TCP Reconnect', meaning: 'Sự kiện thử kết nối lại. Result=SUCCESS không chứng minh ứng dụng đã nhận phản hồi.' },
      { token: 'Content-Length: 3', meaning: 'Độ dài HTTP body được Burp hiển thị; khác 155 byte của sự kiện TCP Receive.' },
    ],
  },
  {
    id: 'services',
    number: '02',
    title: 'Hai dịch vụ mới',
    category: 'Dịch vụ',
    summary: 'SCM tạo cấu hình Auto và LocalSystem. Cấu hình khởi động không đồng nghĩa đã thử reboot.',
    observed: 'Service count: 261 trước chạy, 261 sau A, 263 sau B. Hai tên mới: mssecsvc2.0 và evmdthrukdvwcqn063, đều Auto/LocalSystem. Snapshot ghi service đầu Running, service sau Stopped; Event ID 7045 xuất hiện hai lần.',
    mechanism: 'SCM quản lý cấu hình và vòng đời service. services.exe PID 644 ghi Registry rồi khởi chạy instance theo ImagePath: mẫu với -m security, hoặc cmd.exe gọi tasksche.exe trong ProgramData. Start=2 cấu hình tự khởi động; LocalSystem là tài khoản đặc quyền cục bộ, không phải bằng chứng vượt kiểm soát quyền.',
    inference: 'Hai service thiết lập persistence ở mức cấu hình; ngữ cảnh SYSTEM được quan sát trong lần chạy hiện tại.',
    limit: 'Không reboot nên chưa xác nhận chạy lại thành công. Không suy ra UAC bypass từ thao tác SCM. Startup folders và RunOnce chưa được kiểm toán; trạng thái Stopped không có nguyên nhân đã xác minh.',
    evidence: [
      {
        id: 'E03',
        file: '/screenshots/B_service_mssecsvc_properties_vmware.png',
        title: 'Cấu hình mssecsvc2.0',
        caption: 'Process Hacker cho thấy Auto, LocalSystem, Running và PID 5272 tại thời điểm chụp. Ảnh không chứng minh thực thi sau reboot.',
        source: 'services_after.csv; service_events.log; B_unreachable.csv R772, R780',
      },
    ],
    records: [
      { time: '11:57:36.0995946', event: 'SCM ghi Start=2 cho mssecsvc2.0.', source: 'B_unreachable.csv R772' },
      { time: '11:57:36.1196578', event: 'PID 5272 bắt đầu với -m security.', source: 'B_unreachable.csv R780' },
      { time: '11:57:38.6785954', event: 'SCM ghi Start=2 cho evmdthrukdvwcqn063.', source: 'B_unreachable.csv R1179' },
      { time: '11:57:38.6866410', event: 'cmd.exe PID 1152 bắt đầu qua SCM.', source: 'B_unreachable.csv R1197' },
    ],
    terms: [
      { token: 'Start=2', meaning: 'Cấu hình service tự khởi động khi boot; chưa chứng minh một lần boot thực tế thành công.' },
      { token: 'LocalSystem', meaning: 'Tài khoản dịch vụ đặc quyền cao trên máy cục bộ; không bảo đảm truy cập được mọi tệp.' },
      { token: '-m security', meaning: 'Token dòng lệnh quan sát ở instance service. Ý nghĩa xử lý bên trong binary chưa được giải mã trong bộ chứng cứ.' },
      { token: 'SCM', meaning: 'Service Control Manager: thành phần Windows quản lý service; cầu nối thực thi không nhất thiết trùng cây parent/child của mẫu.' },
    ],
  },
  {
    id: 'payload',
    number: '03',
    title: 'Theo dấu tiến trình',
    category: 'Payload',
    summary: 'Tệp được ghi, service trỏ tới tệp, tiến trình mới chạy: nối chuỗi bằng nhiều nguồn, không chỉ tên.',
    observed: 'PID 5152 ghi C:\\Windows\\tasksche.exe, dài 3,514,368 byte, rồi chạy PID 6724 với /i. Qua service, cmd.exe PID 1152 khởi chạy tasksche.exe PID 3760 trong ProgramData. Tập quy thuộc gồm 15 PID, có cả tiện ích Windows.',
    mechanism: 'Parent/child nối trực tiếp PID 5152 với 6724, và 1152 với 3760. Ở khoảng giữa, SCM là broker: dùng tệp được thả, ImagePath service, timestamp và command line để nối bằng chứng. 271,958 trong 309,281 record B được quy thuộc cho tập 15 PID; đây không phải 15 binary mã độc độc lập.',
    inference: 'Chuỗi cho thấy thả thành phần trung gian rồi chạy payload qua service; tên executable riêng lẻ chưa chứng minh chức năng nội bộ.',
    limit: 'Cầu nối qua SCM không phải quan hệ PPID trực tiếp. PID GUI 1752 xuất hiện sau capture, không thuộc tập 15 PID. Công cụ phân tích và tiến trình nền bị loại khỏi tập quy thuộc.',
    evidence: [
      {
        id: 'E04',
        file: '/screenshots/B_procmon_event_process_identity_vmware.png',
        title: 'Danh tính PID 3760',
        caption: 'Procmon hiển thị tasksche.exe trong ProgramData, PID 3760, parent 1152, Session 0 và SYSTEM. Pane này không tự chứng minh toàn bộ chuỗi hoặc hash của parent.',
        source: 'B_unreachable.csv R1209; B_verified_attribution.md',
      },
    ],
    records: [
      { time: '11:57:38.5925187', event: 'PID 5152 tạo C:\\Windows\\tasksche.exe.', source: 'B_unreachable.csv R1136' },
      { time: '11:57:38.5932685', event: 'WriteFile: 3,514,368 byte, SUCCESS.', source: 'B_unreachable.csv R1137' },
      { time: '11:57:38.6064300', event: 'tasksche.exe /i: PID 6724 bắt đầu.', source: 'B_unreachable.csv R1143' },
      { time: '11:57:38.7258752', event: 'tasksche.exe PID 3760 bắt đầu, parent 1152.', source: 'B_unreachable.csv R1209' },
    ],
    terms: [
      { token: '/i', meaning: 'Switch quan sát trên tasksche.exe PID 6724; không tự dịch thành install khi chưa kiểm tra code.' },
      { token: 'PPID', meaning: 'PID của tiến trình cha trực tiếp; khác quan hệ nhân quả được nối qua SCM.' },
      { token: 'WanaCrypt0r\\wd', meaning: 'Giá trị Registry trỏ working directory C:\\ProgramData\\evmdthrukdvwcqn063, được PID 3760 ghi tại R1213.' },
    ],
  },
  {
    id: 'permissions',
    number: '04',
    title: 'Ẩn thư mục, sửa quyền',
    category: 'Quyền truy cập',
    summary: 'Hai tiện ích Windows được gọi từ payload. Một DACL được ghi thành công; không suy rộng thành quyền toàn máy.',
    observed: 'PID 3760 sinh attrib.exe PID 5808 và icacls.exe PID 2064 dưới SYSTEM. Lệnh là attrib +h . và icacls . /grant Everyone:F /T /C /Q. Procmon ghi SetSecurityFile SUCCESS, Information: DACL, trên b.wnry.',
    mechanism: 'attrib thêm Hidden cho thư mục hiện hành. icacls thêm quyền Full control cho Everyone trên mục tiêu được duyệt, đệ quy cây con, tiếp tục khi lỗi, giảm output thành công. DACL là danh sách kiểm soát truy cập; một mục cho phép không xóa mọi mục từ chối hoặc khóa chia sẻ.',
    inference: 'Parent PID, command line và sự kiện DACL nối thao tác che giấu, sửa quyền với payload PID 3760.',
    limit: 'Không lấy ownership, không chứng minh UAC bypass hoặc quyền trên toàn máy. Chưa có resultant ACL của mọi tệp. /Q không che log Procmon; không có bằng chứng xóa backup từ các lệnh này.',
    evidence: [
      {
        id: 'E05',
        file: '/screenshots/B_procmon_tree_expanded_vmware.png',
        title: 'Tiện ích dưới PID 3760',
        caption: 'Cây Procmon hiển thị attrib.exe 5808 và icacls.exe 2064 dưới tasksche.exe 3760. Command line đầy đủ và lần ghi DACL được đối chiếu bằng CSV, không suy từ tên tiến trình.',
        source: 'B_unreachable.csv R1721, R1724, R1844',
      },
    ],
    records: [
      { time: '11:57:38.8749271', event: 'PID 5808: attrib +h .', source: 'B_unreachable.csv R1721' },
      { time: '11:57:38.8796359', event: 'PID 2064: icacls . /grant Everyone:F /T /C /Q', source: 'B_unreachable.csv R1724' },
      { time: '11:57:39.2573132', event: 'PID 2064 ghi DACL b.wnry: SUCCESS.', source: 'B_unreachable.csv R1844' },
    ],
    terms: [
      { token: 'attrib', meaning: 'Tiện ích Windows hiển thị hoặc thay thuộc tính tệp, thư mục.' },
      { token: '+h', meaning: 'Thêm thuộc tính Hidden; không mã hóa nội dung.' },
      { token: 'icacls', meaning: 'Tiện ích Windows hiển thị hoặc sửa DACL của tệp, thư mục.' },
      { token: '.', meaning: 'Thư mục hiện hành: C:\\ProgramData\\evmdthrukdvwcqn063\\ trong hai Process Start; không phải toàn ổ C.' },
      { token: '/grant', meaning: 'Thêm quyền cấp cho principal; không thay toàn bộ DACL.' },
      { token: 'Everyone:F', meaning: 'Yêu cầu Full control cho principal Everyone trên mục tiêu được duyệt; không chuyển ownership.' },
      { token: '/T', meaning: 'Áp dụng cho cây thư mục con và tệp được duyệt.' },
      { token: '/C', meaning: 'Tiếp tục xử lý dù gặp lỗi; không bảo đảm mọi mục đều thành công.' },
      { token: '/Q', meaning: 'Không in thông báo thành công; không loại bỏ sự kiện khỏi Procmon.' },
    ],
  },
  {
    id: 'files',
    number: '05',
    title: 'Ba tệp, tác động xác thực',
    category: 'Dữ liệu',
    summary: 'Đúng ba decoy đổi path và SHA-256. Header được đọc từ artifact, không suy ra từ extension.',
    observed: 'inventory.csv, lab_document.rtf và student_notes.txt đổi thành .WNCRY, có SHA-256 mới. Kích thước sau lần lượt 328, 360, 360 byte. Cả ba có magic WANACRY!; PID 3760 rename .WNCRYT thành .WNCRY rồi chuyển original sang Temp.',
    mechanism: 'Procmon ghi thứ tự tạo, ghi và rename; artifact sao chép cung cấp raw bytes, header và hash. Offset 8..11 chứa uint32 little-endian 256; offset 12..267 có block 256 byte. FAST IO DISALLOWED theo sau bởi IRP SUCCESS là fallback I/O, không tự chứng minh thao tác thất bại.',
    inference: 'Path, hash, header và chuỗi I/O cùng xác nhận tác động lên ba decoy trong B; extension riêng lẻ không đủ.',
    limit: 'Chưa xác định thuật toán crypto từ giá trị 256. Baseline không lưu kích thước trước chạy. Rename original sang Temp không chứng minh xóa an toàn; không suy ra toàn máy bị mã hóa hoặc không thể phục hồi.',
    evidence: [
      {
        id: 'E06',
        file: '/screenshots/B_procmon_rename_properties_vmware.png',
        title: 'Rename được ghi nhận',
        caption: 'SetRenameInformationFile SUCCESS lúc 11:57:40.1701372: inventory.csv.WNCRYT thành inventory.csv.WNCRY, ReplaceIfExists: False. Rename không tự chứng minh thuật toán hoặc nội dung bị biến đổi.',
        source: 'B_unreachable.csv R2617',
      },
      {
        id: 'E07',
        file: '/screenshots/B_decoys_encrypted_host_verified_vmware.png',
        title: 'Ba decoy sau lần chạy B',
        caption: 'Explorer hiển thị ba tên .WNCRY cùng ransom artifacts. SHA-256 và header được xác minh từ artifact riêng; ảnh chỉ hỗ trợ bối cảnh.',
        source: 'decoys_before.csv; decoys_after_hashes.csv; B_verified_files.md',
      },
    ],
    records: [
      { time: '11:57:40.1701372', event: 'inventory.csv.WNCRYT đổi thành .WNCRY.', source: 'B_unreachable.csv R2617' },
      { time: '11:57:40.1730523', event: 'lab_document.rtf.WNCRYT đổi thành .WNCRY.', source: 'B_unreachable.csv R2638' },
      { time: '11:57:40.1813166', event: 'student_notes.txt.WNCRYT đổi thành .WNCRY.', source: 'B_unreachable.csv R2659' },
      { time: '11:58:40.9514099', event: 'Original inventory.csv chuyển sang C:\\Windows\\Temp\\5.WNCRYT.', source: 'B_unreachable.csv R279026' },
    ],
    terms: [
      { token: 'WANACRY!', meaning: 'Magic bytes ở đầu ba artifact; lấy từ tệp đã bảo toàn, không có trong metadata WriteFile.' },
      { token: 'SHA-256', meaning: 'Hash đối chiếu nội dung trước/sau; hash khác xác nhận bytes thay đổi, không xác định thuật toán mã hóa.' },
      { token: '.WNCRYT', meaning: 'Hậu tố tạm được quan sát trước rename; cũng xuất hiện ở đường dẫn original chuyển sang Temp.' },
    ],
  },
  {
    id: 'ransom',
    number: '06',
    title: 'Thông điệp đòi tiền',
    category: 'Giao diện',
    summary: 'Ransom note, shortcut và GUI nối tác động tệp với yêu cầu thanh toán; GUI được quan sát sau capture.',
    observed: '@Please_Read_Me@.txt dài 933 byte, yêu cầu $300 Bitcoin. Shortcut dài 760 byte. cmd.exe chạy batch, cscript.exe chạy m.vbs. GUI PID 1752 xuất hiện lúc 12:00:10, sau cửa sổ Procmon kết thúc 11:58:47.7389115.',
    mechanism: 'cmd.exe xử lý batch, cscript.exe là Windows Script Host xử lý VBS. Note và shortcut là artifact trên đĩa; cửa sổ muộn hiển thị yêu cầu thanh toán. Module GUI và handle hỗ trợ bối cảnh tiến trình, không chứng minh từng API đã được gọi hoặc khả năng giải mã.',
    inference: 'Lớp giao diện trình bày yêu cầu đòi tiền sau tác động dữ liệu; quan sát này khác bằng chứng thanh toán hay giải mã thành công.',
    limit: 'Không theo dõi thanh toán, giải mã hoặc hạ tầng thật. PID 1752 không thuộc tập 15 PID capture B. Ảnh GUI không tự xác minh executable identity; địa chỉ Bitcoin chưa được xác minh ownership.',
    evidence: [
      {
        id: 'E08',
        file: '/screenshots/B_ransom_gui_final_identity_vmware.png',
        title: 'GUI sau capture',
        caption: 'Wana Decrypt0r hiển thị thông báo, deadline, $300 và nút payment/decrypt. Ảnh chứng minh phần trình bày đòi tiền, không chứng minh thanh toán hay khôi phục tệp.',
        source: 'preserve_current.log; handles_modules_decoys_verified.md; B_verified_files.md',
      },
    ],
    records: [
      { time: '11:57:39.9847610', event: 'PID 3888 chạy cmd.exe /c 116221791435459.bat.', source: 'B_unreachable.csv R2279' },
      { time: '11:57:40.0825587', event: 'PID 6096 chạy cscript.exe //nologo m.vbs.', source: 'B_unreachable.csv R2425' },
    ],
    terms: [
      { token: 'cmd.exe /c', meaning: 'Thực thi command được truyền vào rồi kết thúc command interpreter.' },
      { token: 'cscript.exe', meaning: 'Windows Script Host dạng console; ở đây chạy m.vbs.' },
      { token: '//nologo', meaning: 'Không hiển thị banner của Windows Script Host; không chứng minh script chạy ẩn.' },
      { token: '@Please_Read_Me@.txt', meaning: 'Ransom note quan sát được; lời đòi tiền không bảo đảm khả năng giải mã.' },
    ],
  },
];
