// README.md is canonical. R = 1-based CSV data record, excluding the header.
export const report = {
  lead: 'Hai kịch bản có kiểm soát cho kết quả đối lập: endpoint phản hồi thì mẫu thoát; endpoint không tới được thì service, payload và biến đổi ba decoy xuất hiện.',
  findings: [
    {
      id: 'network',
      title: 'Nhánh mạng và kill switch',
      summary: 'A nhận phản hồi rồi thoát 0; B reconnect, không ghi nhận Receive, tiếp tục chuỗi payload.',
      observed: 'A: PID 6520 gửi 100 byte, nhận 155 byte rồi thoát 0. Burp ghi HTTP/1.0 200 OK, Content-Length: 3. B: PID 5152 và 5272 có tổng tám reconnect, hai disconnect. Cả 14 sự kiện mạng A+B đều tới 127.0.0.1:80.',
      steps: [
        { title: 'Điều kiện thử', body: 'Domain kill-switch được ánh xạ loopback; cổng 80 chuyển tới responder 127.0.0.1:8081. A nhận phản hồi; B không tới được endpoint.' },
        { title: 'Đối chiếu nguồn', body: 'Procmon nối PID với TCP; Burp và responder bổ sung HTTP. Bốn hit log gồm ba preflight harness và một request của mẫu, tách bằng timestamp.' },
        { title: 'Nối kết quả', body: 'A: Receive, Disconnect, Exit liên tiếp. B: reconnect rồi service/payload xuất hiện. Hai kết quả hỗ trợ vai trò reachability, chưa chứng minh câu lệnh nhánh nội bộ.' },
      ],
      inference: 'Trạng thái endpoint thay đổi đồng thời với kết quả thực thi: bằng chứng thực nghiệm có đối chứng cho kill switch, không phải bằng chứng dịch ngược status parsing.',
      limit: 'HTTP 200 là quan sát tại responder/Burp, không chứng minh mẫu kiểm tra mã 200 hoặc gọi InternetOpenUrlA. Không có PCAP, DNS ETW hay API hook. Một request không chứng minh C2, beaconing hoặc exfiltration. A vẫn ghi ZoneMap; chỉ ba decoy và service delta được đối chiếu.',
      evidenceIds: ['E01', 'E02'],
      terms: [
        { token: 'Kill switch', meaning: 'Điều kiện môi trường khiến chương trình ngừng hoặc tiếp tục. Domain lab không phải C2 đã xác nhận.' },
        { token: 'TCP Receive / Content-Length', meaning: '155 byte là độ dài sự kiện TCP Receive; Content-Length: 3 thuộc body HTTP. Không thay thế hai đại lượng này cho nhau.' },
        { token: 'TCP Reconnect SUCCESS', meaning: 'Kernel xử lý request thành công; không đồng nghĩa ứng dụng đã kết nối hoặc nhận được response.' },
        { token: 'Exit status 0', meaning: 'PID 6520 kết thúc sạch lúc 11:44:17.8391858; không chứng minh mẫu bị xóa hoặc toàn máy an toàn.' },
      ],
      sources: [
        'A_200.csv: R343 (Start); R461/R464/R475/R478 (Connect/Send/Receive/Disconnect); R479 (Exit).',
        'A_200.csv: R442–R445, R447–R450 (Registry ZoneMap).',
        'B_unreachable.csv: R413/R498/R679/R769, R770 (PID 5152); R828/R1001/R1083/R1129, R1130 (PID 5272).',
        'network_verified.md; A_verified_audit.md; mock_200.log; run_A_200.log; run_B.log.',
      ],
      mitre: [],
    },
    {
      id: 'services',
      title: 'Service và persistence cấu hình',
      summary: 'B thêm hai service Auto/LocalSystem; chưa thử khởi động lại để xác nhận persistence thực thi.',
      observed: 'Service count: baseline 261, sau A 261, sau B 263. mssecsvc2.0 Running, PID 5272; evmdthrukdvwcqn063 Stopped khi snapshot. Cả hai có Start=2, LocalSystem. System Event Log ghi hai Event ID 7045 lúc 11:57:36 và 11:57:38.',
      steps: [
        { title: 'Đăng ký', body: 'SCM ghi Start, ImagePath, ObjectName dưới Services. Actor Registry là services.exe PID 644; không tự chứng minh mẫu ghi trực tiếp hay vượt UAC.' },
        { title: 'Khởi chạy', body: 'SCM chạy mẫu với -m security thành PID 5272. Service thứ hai có ImagePath cmd.exe /c gọi tasksche.exe trong ProgramData, qua PID 1152 rồi 3760.' },
        { title: 'Khoanh kết luận', body: 'Auto tạo cấu hình chạy khi boot; LocalSystem giải thích ngữ cảnh SYSTEM. Chưa reboot nên không xác nhận hai service sẽ chạy lại thành công.' },
      ],
      inference: 'Hai service mới, ImagePath, Start=2 và Event ID 7045 chứng minh persistence được cấu hình. Trạng thái Stopped của service thứ hai được giữ nguyên, không suy đoán nguyên nhân.',
      limit: 'Không reboot; Startup folders, RunOnce/RunOnceEx và Task XML chưa kiểm toán. HKCU/HKLM CurrentVersion\\Run không có delta; Scheduled Tasks không có task mới. Bốn task Defender đổi Disabled sang Ready nhưng chưa xác định provenance, không gán cho mẫu.',
      evidenceIds: ['E03'],
      terms: [
        { token: 'Service / SCM', meaning: 'Service có cấu hình và vòng đời do Service Control Manager quản lý, có thể chạy trước đăng nhập; chương trình thường được người dùng mở trong phiên. services.exe là broker OS, không phải payload.' },
        { token: 'Start=2 / LocalSystem', meaning: 'Auto start và tài khoản đặc quyền cục bộ. SYSTEM không đảm bảo truy cập mọi tệp; tạo service cần quyền SCM thích hợp, không tự vượt kiểm soát quyền.' },
        { token: '-m security', meaning: 'Token command line quan sát ở service instance. Ý nghĩa nội bộ của switch, khả năng quét SMB hoặc mục đích tác giả chưa được chứng minh trong hồ sơ này.' },
        { token: 'mssecsvc2.0', meaning: 'Display name: Microsoft Security Center (2.0) Service. ImagePath trỏ mẫu trong C:\\LabLive\\Sample_ready\\ với -m security; tên hiển thị không xác thực nguồn gốc executable.' },
      ],
      sources: [
        'B_unreachable.csv: R772/R774/R777 (Start/ImagePath/ObjectName mssecsvc2.0); R780 (PID 5272 Start).',
        'B_unreachable.csv: R1179/R1181/R1184 (service evmdthrukdvwcqn063); R1197 (PID 1152 Start).',
        'persistence_verified.md; service_events.log; services_before.csv; services_A_200.csv; services_after.csv.',
      ],
      mitre: [
        { id: 'T1543.003', label: 'Windows Service', reason: 'Hai service mới, Start=2, ImagePath và Event ID 7045.', limit: 'Tin cậy cao cho cấu hình; chưa thử persistence sau reboot.' },
        { id: 'T1036.004', label: 'Masquerade Task or Service', reason: 'Tên Microsoft Security Center (2.0) Service không trùng image mẫu.', limit: 'Tin cậy trung bình: ý định đánh lừa là diễn giải.' },
      ],
    },
    {
      id: 'payload',
      title: 'Thả payload và nối tiến trình',
      summary: 'PID 5152 thả tasksche.exe; chuỗi tiếp tục qua ProgramData và SCM tới PID 3760 SYSTEM.',
      observed: 'PID 5152 ghi C:\\Windows\\tasksche.exe, WriteFile dài 3,514,368 byte, rồi sinh PID 6724 với /i. PID 6724 tạo stage ProgramData; SCM chạy cmd.exe PID 1152, sinh tasksche.exe PID 3760. PID 3760 ghi WanaCrypt0r\\wd.',
      steps: [
        { title: 'Stage đầu', body: 'CreateFile R1136, WriteFile R1137, Process Create R1142 và Start R1143 nối file C:\\Windows\\tasksche.exe với child PID 6724 của mẫu PID 5152.' },
        { title: 'Cầu nối SCM', body: 'PID 6724 thả tasksche.exe dưới ProgramData. ImagePath service trùng file; timestamp và command line nối SCM với PID 1152, sau đó PID 3760.' },
        { title: 'Phân vai', body: 'PID 3760 chạy Session 0, SYSTEM; sinh utility Windows và xử lý file/Registry. Tập 15 PID là lineage được quy thuộc, không phải 15 binary mã độc.' },
      ],
      inference: 'Có dropper, stage trung gian và payload chạy qua service. Chuỗi 5152–6724 là parent/child trực tiếp; đoạn qua SCM là liên kết nhân quả, không phải cây PPID liền mạch.',
      limit: 'Tên payload, /i hoặc DLL được nạp không chứng minh thuật toán, API, tài nguyên ZIP/mật khẩu, chức năng wiper hay elevation. Công cụ phân tích và services.exe không thuộc 15 PID. GUI PID 1752 xuất hiện 12:00:10, ngoài capture kết thúc 11:58:47.7389115.',
      evidenceIds: ['E04'],
      terms: [
        { token: 'Dropper / payload', meaning: 'Tiến trình ghi thành phần khác xuống đĩa rồi kích hoạt. /i chỉ là token quan sát, chưa đủ gọi chắc chắn là install nếu không dịch ngược hoặc hook.' },
        { token: 'Attribution / PPID', meaning: 'Quy thuộc dựa trên PID, parent, command line, timestamp và cầu nối SCM. PID 6724 có PPID 5152, không phải 5272; PID 3760 có PPID 1152.' },
        { token: 'Working directory', meaning: 'C:\\ProgramData\\evmdthrukdvwcqn063; Registry HKLM\\SOFTWARE\\WOW6432Node\\WanaCrypt0r\\wd trỏ tới đây tại R1213. ProgramData không tự cấp quyền mọi tài khoản.' },
        { token: 'Artifact payload', meaning: 'b.wnry, c.wnry, msg\\m_*.wnry, r.wnry, s.wnry, t.wnry, u.wnry, taskdl.exe, taskse.exe, 00000000.pky/.eky/.res, batch/VBS và ransom artifacts. Tên không chứng minh chức năng nội bộ.' },
        { token: '15 PID / 271,958 record', meaning: '5152, 5272, 6724, 1152, 3760, 5808, 2064, 2952, 6992, 3888, 3472, 6096, 6776, 3252, 1532; 87.93% của 309,281 record B. Gồm ba Conhost và ba instance taskdl.exe.' },
      ],
      sources: [
        'B_unreachable.csv: R1136/R1137/R1142/R1143 (stage Windows); R1197 (cmd.exe); R1209 (tasksche.exe PID 3760); R1213 (WanaCrypt0r\\wd).',
        'B_verified_attribution.md; B_verified_files.md; B_verified_processes.json.',
      ],
      mitre: [
        { id: 'T1059.003', label: 'Windows Command Shell', reason: 'cmd.exe /c thực thi tasksche.exe qua ImagePath service.', limit: 'Command line không chứng minh UAC bypass hoặc mọi hành vi bên trong payload.' },
      ],
    },
    {
      id: 'permissions',
      title: 'Ẩn thư mục, sửa quyền DACL',
      summary: 'attrib yêu cầu Hidden; icacls cấp Everyone:F trong working directory, có ít nhất một ghi DACL thành công.',
      observed: 'PID 3760 sinh attrib PID 5808 với attrib +h . và icacls PID 2064 với icacls . /grant Everyone:F /T /C /Q. Cả hai chạy SYSTEM. PID 2064 SetSecurityFile thành công trên b.wnry, detail Information: DACL.',
      steps: [
        { title: 'Xác định mục tiêu', body: 'Dấu . là C:\\ProgramData\\evmdthrukdvwcqn063\\ trong Process Start của hai utility; không phải toàn ổ C. +h yêu cầu thêm thuộc tính Hidden.' },
        { title: 'Đọc quyền', body: '/grant Everyone:F thêm mục cấp Full control. /T duyệt cây con; /C tiếp tục khi lỗi; /Q giảm thông báo thành công, không xóa telemetry Procmon.' },
        { title: 'Kiểm chứng tác động', body: 'R1844 ghi SetSecurityFile DACL SUCCESS trên b.wnry. Đây là bằng chứng sửa ACL thực tế, không chỉ việc một command line đã được tạo.' },
      ],
      inference: 'Utility Windows được payload sử dụng để che giấu artifact và sửa quyền. Quan hệ parent/child cùng thời điểm gắn hai lệnh với PID 3760.',
      limit: 'Ảnh E05 hỗ trợ quan hệ parent 3760 với attrib 5808/icacls 2064; command icacls bị cắt, phải đối chiếu CSV/README để đọc đủ token. Không có resultant ACL đầy đủ cho mọi tệp. Full control không xóa mọi deny ACE, khóa chia sẻ hay cơ chế bảo vệ. /grant không lấy ownership, không phải UAC bypass. Không có bằng chứng xóa shadow copy/backup; không map T1490 hoặc T1027.',
      evidenceIds: ['E05'],
      terms: [
        { token: 'ACL / DACL / ACE', meaning: 'DACL chứa các mục quyền ACE; Windows đối chiếu token với allow/deny. Thêm một mục Full control không thay toàn bộ DACL, không bảo đảm mọi thao tác đều thành công.' },
        { token: 'Everyone:F', meaning: 'Everyone là principal SID S-1-1-0; F là Full control trên mục tiêu cấp quyền. Không chuyển ownership hoặc tự áp dụng lên mọi đối tượng trên máy.' },
        { token: 'attrib +h .', meaning: 'Thêm thuộc tính Hidden cho thư mục hiện hành; không mã hóa hoặc obfuscate nội dung, không tự chứng minh thay đổi MFT cụ thể.' },
        { token: 'Living off the Land', meaning: 'Sử dụng utility sẵn có của Windows trong chuỗi hành vi. Bản thân attrib.exe, icacls.exe và Conhost.exe không vì thế trở thành binary mã độc.' },
      ],
      sources: [
        'B_unreachable.csv: R1721 (attrib Start); R1724 (icacls Start); R1844 (SetSecurityFile DACL SUCCESS).',
        'B_verified_attribution.md; README.md: mục 4, hành vi 4; mục 7, command tokens.',
      ],
      mitre: [
        { id: 'T1564.001', label: 'Hidden Files and Directories', reason: 'Command attrib +h . đặt Hidden cho mục tiêu.', limit: 'Không phải T1027; không chứng minh nội dung được obfuscate.' },
        { id: 'T1222.001', label: 'Windows File and Directory Permissions Modification', reason: 'icacls /grant Everyone:F và ghi DACL SUCCESS.', limit: 'Tin cậy cao cho ACL change; không phải ownership hoặc T1490.' },
      ],
    },
    {
      id: 'files',
      title: 'Biến đổi đúng ba tệp decoy',
      summary: 'Ba decoy đổi path và hash, có header WANACRY!; không suy rộng thành mọi tệp trên máy.',
      observed: 'inventory.csv, lab_document.rtf và student_notes.txt thành .WNCRY, kích thước sau lần lượt 328, 360, 360 byte. Ba rename thành công tại R2617/R2638/R2659. Artifact có WANACRY!, uint32 little-endian 256 ở offset 8..11 và block 256 byte ở 12..267.',
      steps: [
        { title: 'Đối chiếu baseline', body: 'Ba tệp ở C:\\Users\\bachdeptrai\\Documents\\IAM302_Decoys_20261008 có SHA-256 trước chạy. A giữ nguyên path/hash; B có artifact mới với path/hash thay đổi.' },
        { title: 'Theo dòng I/O', body: 'PID 3760 tạo .WNCRYT, ghi nhiều vùng, rename sang .WNCRY tại 11:57:40.1701372/.1730523/.1813166; original được chuyển sang C:\\Windows\\Temp\\<N>.WNCRYT khoảng 11:58:40.951–.953.' },
        { title: 'Đọc artifact', body: 'Header và SHA-256 lấy từ file đã sao chép, không từ WriteFile CSV. Ảnh rename và Explorer hỗ trợ tên/path; riêng ảnh hoặc extension không chứng minh biến đổi nội dung.' },
      ],
      inference: 'Chuỗi ghi/rename thuộc PID 3760, path/hash thay đổi và container nhất quán hỗ trợ tác động mã hóa trên đúng ba decoy; không đủ xác định thuật toán hoặc quản lý khóa.',
      limit: 'Không có raw bytes trong Procmon. Giá trị 256 không tự chứng minh RSA-2048, AES hoặc key size. Không có baseline size; write length 36/74/70 không thay thế kích thước trước chạy. Rename không bảo đảm an toàn khi mất điện. Chưa kiểm tra backup, VSS, vùng chưa cấp phát hoặc khả năng khôi phục.',
      evidenceIds: ['E06', 'E07'],
      terms: [
        { token: 'WANACRY!', meaning: 'Magic bytes 57 41 4E 41 43 52 59 21 từ artifact tại offset 0. Chứng cứ định dạng container, không chứng minh lời gọi CryptoAPI.' },
        { token: 'FAST IO DISALLOWED', meaning: 'Được theo ngay bởi ghi IRP SUCCESS: fallback I/O, không phải bằng chứng mã hóa thất bại.' },
        { token: 'Original / Temp', meaning: 'Ghi đè rồi di chuyển original sang Temp không chứng minh secure wipe, xóa vĩnh viễn hoặc không thể phục hồi.' },
        { token: 'inventory.csv — SHA-256', meaning: 'Trước: B540FE2588CBAC784D685611B4E62FBF3DABDC03E5DEC0402A2C634756DF8EC4. Sau: 918F8918E203A7CA3124092C26E0C6F33F920FBEB7A9C67DAFC3705CA6D0D341 (328 byte).' },
        { token: 'lab_document.rtf — SHA-256', meaning: 'Trước: C369AE736604EC60D7307134197A251CDD6472EEB15720E6EE5DF56ABBD01E13. Sau: 8F75DB912721C122753D48B06FE56F7A438BBBE8CCB5AA7BA61D4978449A99A8 (360 byte).' },
        { token: 'student_notes.txt — SHA-256', meaning: 'Trước: 0F855BDB7C9C9E29BA4BAC8E446C5190C8D1FF90784376AEECA759F5CCE1FBB1. Sau: D6BB94CD8914974A5D41404819E387297DE7CFD0B31E4230D311BA7DFC4FFE95 (360 byte).' },
      ],
      sources: [
        'B_unreachable.csv: R2617/R2638/R2659 (.WNCRYT rename sang .WNCRY); R279026/R279034/R279042 (original rename sang Temp).',
        'B_verified_files.md; handles_modules_decoys_verified.md; decoys_before.csv; decoys_after_hashes.csv; encrypted_decoys/.',
      ],
      mitre: [
        { id: 'T1486', label: 'Data Encrypted for Impact', reason: 'Ba decoy đổi path/hash, container .WNCRY và header từ artifact.', limit: 'Tin cậy cao trong phạm vi ba decoy; chưa chứng minh thuật toán hoặc toàn máy bị mã hóa.' },
      ],
    },
    {
      id: 'ransom',
      title: 'Ransom note, shortcut và GUI',
      summary: 'Note đòi $300 Bitcoin; batch/VBS và GUI được quan sát, chưa kiểm chứng thanh toán hoặc giải mã.',
      observed: '@Please_Read_Me@.txt dài 933 byte, đòi $300 tới 115p7UMMngoj1pMvkpHijcRdfJNXj6LrLn. Shortcut dài 760 byte. PID 3888 chạy batch; PID 6096 chạy cscript.exe //nologo m.vbs. GUI PID 1752 xuất hiện lúc 12:00:10, sau capture B.',
      steps: [
        { title: 'Tạo artifact', body: 'PID 3760 tạo ransom artifacts. cmd.exe /c 116221791435459.bat và cscript.exe //nologo m.vbs được ghi trong capture; chức năng chi tiết cần đối chiếu nội dung script.' },
        { title: 'Quan sát giao diện', body: 'Ảnh GUI hiển thị yêu cầu $300, Bitcoin address, hai deadline và nút payment/decrypt. Shortcut nối người dùng với decryptor GUI; ảnh không xác nhận giao dịch.' },
        { title: 'Tách cửa sổ đo', body: 'PID 1752 và snapshot module/handle muộn nằm ngoài capture. Working directory chung nối GUI với artifact, không biến PID này thành thành viên tập 15 PID.' },
      ],
      inference: 'Note, shortcut và GUI là lớp trình bày tống tiền sau tác động file. Module MFC/RichEdit/Common Controls phù hợp với giao diện quan sát, không chứng minh từng API đã gọi.',
      limit: 'Không theo dõi thanh toán, giải mã hoặc hạ tầng thật; ownership ví và giao dịch blockchain chưa xác minh. Ảnh không chứng minh executable identity hay service sở hữu cửa sổ. Không suy ra SystemParametersInfoW hoặc crypto từ DLL presence; không khẳng định nút chắc chắn hoạt động hay không hoạt động.',
      evidenceIds: ['E08'],
      terms: [
        { token: 'cmd.exe /c / cscript.exe //nologo', meaning: '/c chạy command rồi kết thúc; //nologo tắt banner Windows Script Host. Token không mô tả toàn bộ API hoặc mục đích của batch/VBS.' },
        { token: 'DLL presence', meaning: 'bcrypt.dll, cryptsp.dll, rsaenh.dll được nạp không chứng minh AES/RSA hay API đã chạy. DLL absence cũng không chứng minh tuyệt đối thiếu capability.' },
        { token: 'Handle snapshot', meaning: 'Log 11:57 dùng handle <PID> là tìm chuỗi, không phải dump riêng tiến trình. Snapshot 12:35:55 mới dùng handle -p <PID>; không trộn hai phạm vi.' },
        { token: '@Please_Read_Me@.txt — SHA-256', meaning: '0E5ECE918132A2B1A190906E74BECB8E4CED36EEC9F9D1C70F5DA72AC4C6B92A; 933 byte.' },
        { token: '@WanaDecryptor@.exe.lnk — SHA-256', meaning: '28006234CFCDADEC26647CA6690E215B26CBC04CCDAC5F015408D943BF24733B; 760 byte.' },
      ],
      sources: [
        'B_unreachable.csv: R2279 (cmd.exe batch PID 3888 Start); R2425 (cscript.exe PID 6096 Start).',
        'B_verified_files.md; handles_modules_decoys_verified.md; preserve_current.log.',
      ],
      mitre: [
        { id: 'T1059.003', label: 'Windows Command Shell', reason: 'cmd.exe /c 116221791435459.bat được quan sát.', limit: 'Không suy diễn mọi nhánh batch nếu chưa đối chiếu nội dung.' },
        { id: 'T1059.005', label: 'Visual Basic', reason: 'cscript.exe //nologo m.vbs chạy trong capture.', limit: 'Chứng minh command thực thi VBS; không tự xác nhận từng API trong script.' },
      ],
    },
  ],
  experiment: {
    summary: 'Hai lần chạy có kiểm soát ngày 2026-10-08 (UTC+7), Windows 10 build 19044, tài khoản DESKTOP-V5VC9B3\\bachdeptrai. Procmon, PowerShell, responder, service/task/Run delta, Event 7045 và ba decoy là các nguồn đối chiếu.',
    steps: [
      'Giữ baseline ba decoy và service list 261 mục; domain kill-switch ánh xạ loopback. B tắt NIC; không dùng hạ tầng threat actor.',
      'A: responder trả HTTP 200. PID 6520 thoát 0; ba decoy nguyên path/SHA-256; service count 261. CSV có 1,710 record.',
      'B: responder không tới được. CSV có 309,281 record; 271,958 thuộc 15 PID, 37,323 nền/loại trừ. Hai service mới và ba artifact .WNCRY được đối chiếu.',
      'Đọc R theo data record 1-based, bỏ header, dùng csv.DictReader; newline nhúng khiến số dòng văn bản không tương đương record index.',
      'verification.log được README ghi nhận pass checksum, record count A/B, ba hash A, ba header/hash B và tập 15 PID. Đây là kết quả hồ sơ, không phải lần chạy lại trên trang này.',
    ],
    limits: [
      'Không có PCAP, DNS ETW, debugger, API hook hoặc memory trace; không chứng minh code branch, status parsing, thuật toán hay quản lý khóa.',
      'Không reboot; không kiểm toán Startup folders, RunOnce/RunOnceEx, Task XML, thanh toán, giải mã hoặc phục hồi.',
      'NIC B bị tắt. Không quan sát SMB/C2/exfiltration bên ngoài không có nghĩa binary không có capability đó.',
      'Ảnh hỗ trợ bối cảnh UI; CSV/log/hash là nguồn định lượng. Capture gốc đầy đủ vẫn lưu cục bộ; trích lục văn bản chọn lọc đã công khai kèm manifest, hash nguồn và ghi chú che thông tin.',
      'A vẫn ghi ZoneMap. Chỉ ba decoy có baseline; không kết luận toàn máy bất biến ở A hoặc toàn bộ dữ liệu bị mã hóa ở B.',
    ],
  },
  conclusions: [
    'A và B hỗ trợ quan hệ giữa endpoint reachability với thoát sớm hoặc tiếp tục chuỗi hành vi; cơ chế nhánh nội bộ chưa được dịch ngược.',
    'B có hai service Auto/LocalSystem, chuỗi payload qua SCM, utility sửa thuộc tính/quyền và tác động file được quy thuộc PID 3760.',
    'Đúng ba decoy đổi path/hash thành artifact .WNCRY có WANACRY!; chưa chứng minh thuật toán, secure wipe hoặc mất khả năng phục hồi.',
    'Ransom presentation được quan sát; persistence sau reboot, thanh toán, giải mã và liên lạc hạ tầng thật chưa kiểm chứng.',
  ],
  appendix: {
    faqs: [
      { question: '1. Hành vi ngay sau thực thi?', answer: 'Mẫu kết nối TCP tới loopback đại diện domain kill-switch. A nhận 155 byte rồi thoát 0; B reconnect, không ghi nhận TCP Receive, tiếp tục chuỗi service/payload. Responder/Burp xác nhận HTTP riêng, không chứng minh API status parsing.' },
      { question: '2. Hệ điều hành thay đổi thế nào?', answer: 'A vẫn có ghi ZoneMap nhưng không service mới, ba decoy nguyên hash. B thêm hai service, payload/working directory, Registry WanaCrypt0r\\wd, lệnh Hidden/DACL, ba .WNCRY và ransom artifacts. Không khẳng định biến đổi toàn hệ thống ngoài capture.' },
      { question: '3. Tệp hoặc tiến trình nào sinh ra?', answer: 'C:\\Windows\\tasksche.exe và stage C:\\ProgramData\\evmdthrukdvwcqn063 cùng .wnry, taskdl.exe, taskse.exe, khóa/container, batch/VBS, note/shortcut/GUI. Tập 15 PID gồm utility Windows; GUI PID 1752 đến sau capture, không nằm trong tập này.' },
      { question: '4. Có persistence sau reboot?', answer: 'Hai service Auto/LocalSystem chứng minh cấu hình persistence, chưa chứng minh chạy lại sau reboot vì chưa thử. Run keys chỉ kiểm tra HKCU/HKLM CurrentVersion\\Run; không có task mới, nhưng Startup folders và RunOnce chưa kiểm toán.' },
      { question: '5. Kết nối IP/domain nào?', answer: 'www.iuqerfsodp9ifjaposdfjhgosurijfaewrwergwea.com được ánh xạ 127.0.0.1. Toàn bộ 14 sự kiện mạng được quy thuộc A+B tới 127.0.0.1:80; Burp forwarding host là 127.0.0.1:8081. Không có endpoint công cộng trong tập này.' },
      { question: '6. Giao thức và mục đích?', answer: 'Procmon chứng minh TCP; responder/Burp/log hỗ trợ một HTTP GET của mẫu ở A để kiểm tra endpoint. Ba hit còn lại là harness preflight. Không có PCAP/DNS API trace; một kill-switch request không được gọi là C2.' },
      { question: '7. Điều kiện môi trường làm hành vi đổi thế nào?', answer: 'Responder tới được: mẫu thoát, ba decoy nguyên hash, không service mới. Không tới được: service/payload và biến đổi ba decoy xuất hiện. Đây là đối chứng thực nghiệm; không chứng minh tác giả dùng anti-sandbox hay so sánh riêng status 200.' },
      { question: '8. IOC cốt lõi?', answer: 'SHA-256 mẫu, domain kill-switch, mssecsvc2.0, evmdthrukdvwcqn063, tasksche.exe, working directory, WanaCrypt0r\\wd, .WNCRY/WANACRY!, ransom files và Bitcoin address. Đối chiếu IOC với phạm vi bên dưới; một tên file riêng lẻ không đủ kết luận nhiễm.' },
      { question: '9. MITRE ATT&CK nào được hỗ trợ?', answer: 'T1543.003, T1486, T1564.001, T1222.001, T1059.003, T1059.005; T1036.004 mức trung bình. Không map T1490 từ icacls, T1027 từ attrib, C2 từ kill switch, UAC bypass từ SCM hoặc SMB propagation khi không có traffic. T1204.002 là thao tác harness, không phải kỹ thuật adversary được chứng minh.' },
    ],
    iocs: [
      { value: '24D004A104D4D54034DBCFFC2A4B19A11F39008A575AA614EA04703480B1022C', meaning: 'SHA-256 mẫu thí nghiệm.', limit: 'Identity của file này, không đại diện mọi biến thể.', findingId: 'payload' },
      { value: 'www.iuqerfsodp9ifjaposdfjhgosurijfaewrwergwea.com', meaning: 'Domain kill-switch, ánh xạ loopback trong lab.', limit: 'Không phải C2 được chứng minh.', findingId: 'network' },
      { value: 'mssecsvc2.0', meaning: 'Service, display name Microsoft Security Center (2.0) Service.', limit: 'Cần đối chiếu ImagePath, hash và thời điểm; tên riêng không đủ.', findingId: 'services' },
      { value: 'evmdthrukdvwcqn063', meaning: 'Tên service thứ hai và working directory.', limit: 'Tên quan sát ở lần chạy này; không giả định ổn định mọi biến thể.', findingId: 'services' },
      { value: 'C:\\Windows\\tasksche.exe', meaning: 'Stage do PID 5152 ghi.', limit: 'Đối chiếu lineage và file identity, không chỉ basename.', findingId: 'payload' },
      { value: 'C:\\ProgramData\\evmdthrukdvwcqn063\\', meaning: 'Working directory của payload.', limit: 'Phạm vi đường dẫn quan sát trong lab.', findingId: 'payload' },
      { value: 'HKLM\\SOFTWARE\\WOW6432Node\\WanaCrypt0r\\wd', meaning: 'Registry trỏ working directory.', limit: 'Giá trị quan sát tại B R1213.', findingId: 'payload' },
      { value: '.WNCRY / WANACRY!', meaning: 'Extension và magic container.', limit: 'Đã xác minh đúng ba artifact; riêng extension không chứng minh crypto.', findingId: 'files' },
      { value: '@Please_Read_Me@.txt / @WanaDecryptor@.exe / .lnk', meaning: 'Ransom note, executable GUI và shortcut.', limit: 'Không chứng minh thanh toán hoặc giải mã.', findingId: 'ransom' },
      { value: '115p7UMMngoj1pMvkpHijcRdfJNXj6LrLn', meaning: 'Bitcoin address trong note/GUI.', limit: 'Chưa xác minh ownership hoặc giao dịch blockchain.', findingId: 'ransom' },
    ],
    references: [
      { title: 'MITRE ATT&CK Enterprise techniques', url: 'https://attack.mitre.org/techniques/enterprise/' },
      { title: 'Microsoft — attrib', url: 'https://learn.microsoft.com/windows-server/administration/windows-commands/attrib' },
      { title: 'Microsoft — icacls', url: 'https://learn.microsoft.com/windows-server/administration/windows-commands/icacls' },
      { title: 'Microsoft — Service start type', url: 'https://learn.microsoft.com/windows/win32/api/winsvc/nf-winsvc-changeserviceconfiga' },
      { title: 'Sysinternals — Process Monitor', url: 'https://learn.microsoft.com/sysinternals/downloads/procmon' },
      { title: 'Sysinternals — Handle', url: 'https://learn.microsoft.com/sysinternals/downloads/handle' },
    ],
  },
};
